
<div class="panel panel-default">

	<div class="panel-heading">AMIC MANILA 2017: ACCOUNT RESET PASSWORD!</div>

		<div class="panel-body">
			<p><b>Good day!</b></p>
			<p>We got a request to reset your Amic Manila Administrator password.</p>
			<p><b>Click the link below to reset your password</b></p>
			<a href="{{ url('password/reset/'.$token) }}" class="btn btn-primary">Reset Password</a>
			<br />
			<small><i>This is autogenerated email, Do not reply this message!</i></small>
		</div>
</div>

